name: Run Karate Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Maven
      run: mvn test

    - name: Upload Karate report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: karate-report
        path: target/karate-reports/